build:
    stage: build
    image: rust:latest
    script:
        - apt-get update
        - apt install -y tree
        - cd rust
        - cargo test
        - cargo package
        - mv /builds/oracularhades/hades-auth/rust/target/package/hades-auth-*.crate /builds/oracularhades/hades-auth/hades-auth.crate
        - tree /
    artifacts:
        paths:
            - /builds/oracularhades/hades-auth/hades-auth.crate