build:
    stage: build
    image: rust:latest
    script:
        - apt-get update
        - apt install -y tree zip
        - cd rust
        - cargo test
        - cargo package
        - cd target/package
        - find . -type f -name '*.crate' -delete
        - mkdir /builds/oracularhades/output
        - mv hades_auth* /builds/oracularhades/output
        - zip -r /builds/oracularhades/hades-auth/output.zip /builds/oracularhades/output
        - tree /
    artifacts:
        paths:
            - /builds/oracularhades/hades-auth/output.zip