build:
    stage: build
    image: rust:latest
    script:
        - apt-get update
        - apt install -y tree zip
        - cd rust
        - cargo test
        - cargo package
        - cd target/package
        - tree /
    artifacts:
        paths:
            - /builds/oracularhades/hades-auth/output.zip