build:
    stage: build
    image: rust:latest
    script:
        - apt-get update
        - apt install -y tree zip
        - cd rust
        - cargo test
        - cargo package
        - cd target/package
        - find . -type f -name '*.crate' -delete
        - mv frank_jwt* /builds/oracularhades/output
        - zip -r /builds/oracularhades/output .
        - tree
    artifacts:
        paths:
        - /builds/oracularhades/output.zip